// Generated by gencpp from file sin/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SIN_MESSAGE_ADDTWOINTS_H
#define SIN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <sin/AddTwoIntsRequest.h>
#include <sin/AddTwoIntsResponse.h>


namespace sin
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace sin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sin::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::sin::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::sin::AddTwoInts > {
  static const char* value()
  {
    return "sin/AddTwoInts";
  }

  static const char* value(const ::sin::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::sin::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::sin::AddTwoInts > 
template<>
struct MD5Sum< ::sin::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sin::AddTwoInts >::value();
  }
  static const char* value(const ::sin::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sin::AddTwoIntsRequest> should match 
// service_traits::DataType< ::sin::AddTwoInts > 
template<>
struct DataType< ::sin::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::sin::AddTwoInts >::value();
  }
  static const char* value(const ::sin::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sin::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::sin::AddTwoInts > 
template<>
struct MD5Sum< ::sin::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sin::AddTwoInts >::value();
  }
  static const char* value(const ::sin::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sin::AddTwoIntsResponse> should match 
// service_traits::DataType< ::sin::AddTwoInts > 
template<>
struct DataType< ::sin::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::sin::AddTwoInts >::value();
  }
  static const char* value(const ::sin::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIN_MESSAGE_ADDTWOINTS_H
