// Generated by gencpp from file plot_linear/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PLOT_LINEAR_MESSAGE_ADDTWOINTS_H
#define PLOT_LINEAR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <plot_linear/AddTwoIntsRequest.h>
#include <plot_linear/AddTwoIntsResponse.h>


namespace plot_linear
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace plot_linear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plot_linear::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::plot_linear::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::plot_linear::AddTwoInts > {
  static const char* value()
  {
    return "plot_linear/AddTwoInts";
  }

  static const char* value(const ::plot_linear::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::plot_linear::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::plot_linear::AddTwoInts > 
template<>
struct MD5Sum< ::plot_linear::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plot_linear::AddTwoInts >::value();
  }
  static const char* value(const ::plot_linear::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plot_linear::AddTwoIntsRequest> should match 
// service_traits::DataType< ::plot_linear::AddTwoInts > 
template<>
struct DataType< ::plot_linear::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::plot_linear::AddTwoInts >::value();
  }
  static const char* value(const ::plot_linear::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plot_linear::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::plot_linear::AddTwoInts > 
template<>
struct MD5Sum< ::plot_linear::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plot_linear::AddTwoInts >::value();
  }
  static const char* value(const ::plot_linear::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plot_linear::AddTwoIntsResponse> should match 
// service_traits::DataType< ::plot_linear::AddTwoInts > 
template<>
struct DataType< ::plot_linear::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::plot_linear::AddTwoInts >::value();
  }
  static const char* value(const ::plot_linear::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLOT_LINEAR_MESSAGE_ADDTWOINTS_H
