// Generated by gencpp from file mic/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MIC_MESSAGE_ADDTWOINTS_H
#define MIC_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <mic/AddTwoIntsRequest.h>
#include <mic/AddTwoIntsResponse.h>


namespace mic
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace mic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mic::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::mic::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::mic::AddTwoInts > {
  static const char* value()
  {
    return "mic/AddTwoInts";
  }

  static const char* value(const ::mic::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::mic::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::mic::AddTwoInts > 
template<>
struct MD5Sum< ::mic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mic::AddTwoInts >::value();
  }
  static const char* value(const ::mic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mic::AddTwoIntsRequest> should match 
// service_traits::DataType< ::mic::AddTwoInts > 
template<>
struct DataType< ::mic::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::mic::AddTwoInts >::value();
  }
  static const char* value(const ::mic::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mic::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::mic::AddTwoInts > 
template<>
struct MD5Sum< ::mic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mic::AddTwoInts >::value();
  }
  static const char* value(const ::mic::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mic::AddTwoIntsResponse> should match 
// service_traits::DataType< ::mic::AddTwoInts > 
template<>
struct DataType< ::mic::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::mic::AddTwoInts >::value();
  }
  static const char* value(const ::mic::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIC_MESSAGE_ADDTWOINTS_H
